title: Hintbits
author: Oleksii Kliukin
description: >
  Oleskii Kliukin personal page. Still figuring out what to write about.
favicon: "./favicon.ico"

show_excerpts: false

moving:
  avatar_url: "https://avatars0.githubusercontent.com/u/339913?s=460&v=4"
  about_you: Husband, father, software engineer and PostgreSQL contributor.
  date_format: "%b %d"
  back_to: "Home"

  social_links:
    twitter: hintbits
    github:  alexeyklyukin
    rss: RSS
    linkedin: alexeyklyukin

remote_theme: huangyz0918/moving

plugins:
  - jekyll-feed
